# Directories
DATASET_DIR = 'dataset/'
DATASET_IMAGES_DIR = DATASET_DIR + 'images/'
DATASET_ANNOTATIONS_DIR = DATASET_DIR + 'annotations/'

PROCESS_DIR = "process/"
PROCESS_IMAGES_DIR = PROCESS_DIR + 'preprocessed-images/'

PROCESS_TRAIN_DIR = PROCESS_DIR + "train/"
PROCESS_TRAIN_IMAGES_DIR = PROCESS_TRAIN_DIR + "images/"
PROCESS_TRAIN_LABELS_DIR = PROCESS_TRAIN_DIR + "labels/"
PROCESS_TEST_DIR = PROCESS_DIR + "test/"
PROCESS_TEST_IMAGES_DIR = PROCESS_TEST_DIR + "images/"
PROCESS_TEST_LABELS_DIR = PROCESS_TEST_DIR + "labels/"
PROCESS_VALIDATE_DIR = PROCESS_DIR + "validate/"
PROCESS_VALIDATE_IMAGES_DIR = PROCESS_VALIDATE_DIR + "images/"
PROCESS_VALIDATE_LABELS_DIR = PROCESS_VALIDATE_DIR + "labels/"

OUTPUT_DIR = "output/"
# Flags

# Values
INITIALIZE_DIRECTORIES = [
    PROCESS_DIR,
    PROCESS_IMAGES_DIR,
    PROCESS_TRAIN_DIR,
    PROCESS_TRAIN_IMAGES_DIR,
    PROCESS_TRAIN_LABELS_DIR,
    PROCESS_TEST_DIR,
    PROCESS_TEST_IMAGES_DIR,
    PROCESS_TEST_LABELS_DIR,
    PROCESS_VALIDATE_DIR,
    PROCESS_VALIDATE_IMAGES_DIR,
    PROCESS_VALIDATE_LABELS_DIR,
    OUTPUT_DIR,
]
# These must add up to 10, floats are avoided because of float shenanigans
TRAIN_PROPORTION = 7
TEST_PROPORTION = 2
VALIDATE_PROPORTION = 1


